apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aws-cnapp
  namespace: argocd
spec:
  description: AWS CNAPP project
  sourceRepos:
    - <GITHUB_REPOSITORY_URL>
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
